
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
test:
    path: /default
    defaults:  { _controller: AppBundle:Default:test }

users:
    type: rest  # Required for ``RestYamlLoader`` to process imported routes
    prefix: /api
    resource: "@UberScheduleBundle/Resources/config/routing.yml"

user_redirect:
    path: /user/redirect
    defaults: { _controller: UberScheduleBundle:User:redirect }

user_session:
    path: /api/user/test
    defaults: { _controller: UberScheduleBundle:User:userTest }

user_uber:
    path: /user/uber/f6d75c949cda2517b826cacba5523792
    defaults: { _controller: UberScheduleBundle:User:uberRedirect }

get_jwt_token:
    defaults: { _controller: UberScheduleBundle:User:getToken} 
    path: /api/user/getToken