parameters:
    uberClient:
        baseurl: https://api.uber.com/v1/
        sandboxUrl: https://sandbox-api.uber.com/
        idClient: rA_xJyeKF3srdRgdoGYlfPLG6eLA-uno
        serverToken: YU7tAiBg_SUJ_tBDBh0SJZwbhcVb1pLrqrGVcIn7
        secretClient: nFiAI2J9uMY3Wk5YIjRvPQ4MtMBmlsf0CLht6Lzd
        useSandbox: true
    uberAuth:
        baseurl:  https://login.uber.com/
        sandboxUrl: https://sandbox-api.uber.com/
        idClient: rA_xJyeKF3srdRgdoGYlfPLG6eLA-uno
        serverToken: YU7tAiBg_SUJ_tBDBh0SJZwbhcVb1pLrqrGVcIn7
        secretClient: nFiAI2J9uMY3Wk5YIjRvPQ4MtMBmlsf0CLht6Lzd
        useSandbox: true